In [33]:
import pandas as pd

In [34]:
df = pd.read_csv('../data/raw/hospitalflow_integrated_inventory_disease_dataset_2025(1).csv')

In [35]:
# see the columns
df.columns.to_list()

to_drop = [
 'facility_id',
 'facility_name',
 'stockout_flag', 
 'opening_stock',
 'closing_stock',
 'zip_department_match',
 'disease_department_match',
 'department_emergency_admissions',
 'department_unique_diseases',
 'dominant_disease_id',
 'dominant_disease_name',
 'dominant_disease_category',
 'dominant_disease_admissions',
 'hospital_admissions',
 'hospital_emergency_admissions',
 'hospital_elective_admissions',
 'unique_diseases_observed',
 'disease_cat_cardiac_admissions',
 'disease_cat_endocrine_admissions',
 'disease_cat_hematological_admissions',
 'disease_cat_infectious_admissions',
 'disease_cat_neurological_admissions',
 'disease_cat_orthopedic_admissions',
 'disease_cat_pediatric_admissions',
 'disease_cat_renal_admissions',
 'disease_cat_respiratory_admissions',
 'disease_cat_surgical_admissions',
 'disease_cat_trauma_admissions',
 'hospital_admissions_7d_avg',
 'hospital_emergency_admissions_7d_avg',
 'department_admissions_7d_avg',
 'hospital_admissions_7d_change_pct',
 'department_admissions_7d_change_pct',
 'facility_stock_value_kes',
 'facility_lag_1d_usage',
 'facility_lag_7d_usage',
 'facility_rolling_7d_usage',
 'facility_rolling_14d_usage',
 'facility_rolling_30d_usage',
 'facility_usage_std_14d',
 'facility_forecast_7d_baseline',
 'facility_reorder_point_units',
 'facility_days_of_stock',
 'facility_stockout_risk',
 'department_lag_1d_usage',
 'department_lag_7d_usage',
 'department_rolling_7d_usage',
 'department_rolling_14d_usage',
 'department_rolling_30d_usage',
 'department_usage_std_14d',
 'department_usage_share_of_product',
 'department_usage_change_pct',
 'day_of_week', 'month', 'is_weekend'
 ]

In [36]:
df['facility_id'].value_counts()

facility_id
FAC001    17700
Name: count, dtype: int64

In [37]:
df['unit'].value_counts() # pending cleaning, Cross validation

unit
Box (100)      5900
Box (50)       3540
Box (25)       2360
Box (20)       1180
Pack (100)     1180
Box (10)       1180
Pack (500g)    1180
Pack (50)      1180
Name: count, dtype: int64

In [38]:
df['zip_department_match'].sample(5)

14508        NaN
2224         NaN
9137     Surgery
2521         NaN
5398     Surgery
Name: zip_department_match, dtype: object

In [39]:
df[['zip_department_match',
 'disease_department_match',
 'department_admissions',
 'department_emergency_admissions',
 'department_unique_diseases',
 'dominant_disease_id',
 'dominant_disease_name',
 'dominant_disease_category',
 'dominant_disease_admissions',
 'hospital_admissions',
 'hospital_emergency_admissions',
 'hospital_elective_admissions']].sample(5)

,zip_department_match,disease_department_match,department_admissions,department_emergency_admissions,department_unique_diseases,dominant_disease_id,dominant_disease_name,dominant_disease_category,dominant_disease_admissions,hospital_admissions,hospital_emergency_admissions,hospital_elective_admissions
3515,Surgery,True,2.0,0.0,2.0,4.0,Sepsis,Infectious,1.0,14,6,8
3118,NaN,False,22.0,7.0,13.0,6.0,Diabetes Mellitus,Endocrine,2.0,22,7,15
17541,Surgery,True,7.0,4.0,6.0,1.0,Acute Myocardial Infarction,Cardiac,2.0,23,11,12
5466,Surgery,True,9.0,3.0,7.0,1.0,Acute Myocardial Infarction,Cardiac,2.0,20,6,14
14111,Emergency,True,2.0,1.0,2.0,13.0,Gallstones,Surgical,1.0,20,7,13

engineered features
'facility_stock_value_kes',
'department_lag_1d_usage',
'department_lag_7d_usage',
'department_usage_std_14d',
'department_usage_share_of_product',
'department_usage_change_pct',

In [40]:
# pd.set_option('display.max_rows', None)      # show all rows
# pd.set_option('display.max_columns', None)   # show all columns (bonus)
# pd.set_option('display.width', None) 
df.head(20)

,date,facility_id,facility_name,department,product_id,product_name,category,unit,supplier,opening_stock,...,facility_days_of_stock,facility_stockout_risk,department_lag_1d_usage,department_lag_7d_usage,department_rolling_7d_usage,department_rolling_14d_usage,department_rolling_30d_usage,department_usage_std_14d,department_usage_share_of_product,department_usage_change_pct
0,2025-01-01,FAC001,Hospital A,Emergency,MED001,Nitrile Gloves,PPE,Box (100),MedSupply Kenya,1303,...,NaN,Low,NaN,NaN,NaN,NaN,NaN,NaN,0.192,NaN
1,2025-01-01,FAC001,Hospital A,Emergency,MED002,5ml Syringes,Injection Supplies,Box (100),AfyaMed Distributors,477,...,NaN,Low,NaN,NaN,NaN,NaN,NaN,NaN,0.188,NaN
2,2025-01-01,FAC001,Hospital A,Emergency,MED003,10ml Syringes,Injection Supplies,Box (100),AfyaMed Distributors,352,...,NaN,Low,NaN,NaN,NaN,NaN,NaN,NaN,0.000,NaN
3,2025-01-01,FAC001,Hospital A,Emergency,MED004,IV Cannulas 20G,IV Supplies,Box (50),MedSupply Kenya,239,...,NaN,Low,NaN,NaN,NaN,NaN,NaN,NaN,0.000,NaN
4,2025-01-01,FAC001,Hospital A,Emergency,MED005,IV Giving Sets,IV Supplies,Box (20),HealthLink Supplies,157,...,NaN,Low,NaN,NaN,NaN,NaN,NaN,NaN,0.000,NaN
5,2025-01-01,FAC001,Hospital A,Emergency,MED006,Sterile Gauze 10x10cm,Wound Care,Pack (100),MedSupply Kenya,507,...,NaN,Low,NaN,NaN,NaN,NaN,NaN,NaN,0.000,NaN
6,2025-01-01,FAC001,Hospital A,Emergency,MED007,Surgical Masks,PPE,Box (50),HealthLink Supplies,610,...,NaN,Low,NaN,NaN,NaN,NaN,NaN,NaN,0.000,NaN
7,2025-01-01,FAC001,Hospital A,Emergency,MED008,Alcohol Swabs,Disinfection,Box (100),AfyaMed Distributors,399,...,NaN,Low,NaN,NaN,NaN,NaN,NaN,NaN,0.203,NaN
8,2025-01-01,FAC001,Hospital A,Emergency,MED009,Urinary Catheters 16Fr,Urology,Box (10),CarePlus Medical,92,...,NaN,Low,NaN,NaN,NaN,NaN,NaN,NaN,0.000,NaN
9,2025-01-01,FAC001,Hospital A,Emergency,MED010,Malaria RDT Kits,Diagnostics,Box (25),CarePlus Medical,162,...,NaN,Low,NaN,NaN,NaN,NaN,NaN,NaN,0.217,NaN
10,2025-01-01,FAC001,Hospital A,Emergency,MED011,Pregnancy Test Kits,Diagnostics,Box (50),HealthLink Supplies,103,...,NaN,Low,NaN,NaN,NaN,NaN,NaN,NaN,0.000,NaN
11,2025-01-01,FAC001,Hospital A,Emergency,MED012,IV Extension Sets,IV Supplies,Box (25),MedSupply Kenya,167,...,NaN,Low,NaN,NaN,NaN,NaN,NaN,NaN,0.000,NaN
12,2025-01-01,FAC001,Hospital A,Emergency,MED013,Examination Gloves,PPE,Box (100),MedSupply Kenya,824,...,NaN,Low,NaN,NaN,NaN,NaN,NaN,NaN,0.000,NaN
13,2025-01-01,FAC001,Hospital A,Emergency,MED014,Cotton Wool,Wound Care,Pack (500g),HealthLink Supplies,281,...,NaN,Low,NaN,NaN,NaN,NaN,NaN,NaN,0.065,NaN
14,2025-01-01,FAC001,Hospital A,Emergency,MED015,Specimen Containers,Diagnostics,Pack (50),CarePlus Medical,162,...,NaN,Low,NaN,NaN,NaN,NaN,NaN,NaN,0.000,NaN
15,2025-01-01,FAC001,Hospital A,ICU,MED001,Nitrile Gloves,PPE,Box (100),MedSupply Kenya,1346,...,NaN,Low,NaN,NaN,NaN,NaN,NaN,NaN,0.178,NaN
16,2025-01-01,FAC001,Hospital A,ICU,MED002,5ml Syringes,Injection Supplies,Box (100),AfyaMed Distributors,498,...,NaN,Low,NaN,NaN,NaN,NaN,NaN,NaN,0.293,NaN
17,2025-01-01,FAC001,Hospital A,ICU,MED003,10ml Syringes,Injection Supplies,Box (100),AfyaMed Distributors,364,...,NaN,Low,NaN,NaN,NaN,NaN,NaN,NaN,0.000,NaN
18,2025-01-01,FAC001,Hospital A,ICU,MED004,IV Cannulas 20G,IV Supplies,Box (50),MedSupply Kenya,248,...,NaN,Low,NaN,NaN,NaN,NaN,NaN,NaN,0.000,NaN
19,2025-01-01,FAC001,Hospital A,ICU,MED005,IV Giving Sets,IV Supplies,Box (20),HealthLink Supplies,162,...,NaN,Low,NaN,NaN,NaN,NaN,NaN,NaN,0.000,NaN

In [41]:
df.iloc[[0,15,75]]

,date,facility_id,facility_name,department,product_id,product_name,category,unit,supplier,opening_stock,...,facility_days_of_stock,facility_stockout_risk,department_lag_1d_usage,department_lag_7d_usage,department_rolling_7d_usage,department_rolling_14d_usage,department_rolling_30d_usage,department_usage_std_14d,department_usage_share_of_product,department_usage_change_pct
0,2025-01-01,FAC001,Hospital A,Emergency,MED001,Nitrile Gloves,PPE,Box (100),MedSupply Kenya,1303,...,NaN,Low,NaN,NaN,NaN,NaN,NaN,NaN,0.192,NaN
15,2025-01-01,FAC001,Hospital A,ICU,MED001,Nitrile Gloves,PPE,Box (100),MedSupply Kenya,1346,...,NaN,Low,NaN,NaN,NaN,NaN,NaN,NaN,0.178,NaN
75,2025-01-02,FAC001,Hospital A,Emergency,MED001,Nitrile Gloves,PPE,Box (100),MedSupply Kenya,1075,...,NaN,Low,55.0,NaN,55.0,55.0,55.0,NaN,0.246,-1.818

In [42]:
df[df['date'] == '2025-01-02']

,date,facility_id,facility_name,department,product_id,product_name,category,unit,supplier,opening_stock,...,facility_days_of_stock,facility_stockout_risk,department_lag_1d_usage,department_lag_7d_usage,department_rolling_7d_usage,department_rolling_14d_usage,department_rolling_30d_usage,department_usage_std_14d,department_usage_share_of_product,department_usage_change_pct
75,2025-01-02,FAC001,Hospital A,Emergency,MED001,Nitrile Gloves,PPE,Box (100),MedSupply Kenya,1075,...,NaN,Low,55.0,NaN,55.0,55.0,55.0,NaN,0.246,-1.818
76,2025-01-02,FAC001,Hospital A,Emergency,MED002,5ml Syringes,Injection Supplies,Box (100),AfyaMed Distributors,398,...,NaN,Low,20.0,NaN,20.0,20.0,20.0,NaN,0.250,-5.000
77,2025-01-02,FAC001,Hospital A,Emergency,MED003,10ml Syringes,Injection Supplies,Box (100),AfyaMed Distributors,296,...,NaN,Low,12.0,NaN,12.0,12.0,12.0,NaN,0.000,8.333
78,2025-01-02,FAC001,Hospital A,Emergency,MED004,IV Cannulas 20G,IV Supplies,Box (50),MedSupply Kenya,190,...,NaN,Low,10.0,NaN,10.0,10.0,10.0,NaN,0.000,-10.000
79,2025-01-02,FAC001,Hospital A,Emergency,MED005,IV Giving Sets,IV Supplies,Box (20),HealthLink Supplies,118,...,NaN,Low,9.0,NaN,9.0,9.0,9.0,NaN,0.000,44.444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,2025-01-02,FAC001,Hospital A,Theatre,MED011,Pregnancy Test Kits,Diagnostics,Box (50),HealthLink Supplies,82,...,NaN,Low,4.0,NaN,4.0,4.0,4.0,NaN,0.000,-25.000
146,2025-01-02,FAC001,Hospital A,Theatre,MED012,IV Extension Sets,IV Supplies,Box (25),MedSupply Kenya,131,...,NaN,Low,4.0,NaN,4.0,4.0,4.0,NaN,0.371,0.000
147,2025-01-02,FAC001,Hospital A,Theatre,MED013,Examination Gloves,PPE,Box (100),MedSupply Kenya,627,...,NaN,Low,31.0,NaN,31.0,31.0,31.0,NaN,0.000,-16.129
148,2025-01-02,FAC001,Hospital A,Theatre,MED014,Cotton Wool,Wound Care,Pack (500g),HealthLink Supplies,228,...,NaN,Low,8.0,NaN,8.0,8.0,8.0,NaN,0.000,12.500
149,2025-01-02,FAC001,Hospital A,Theatre,MED015,Specimen Containers,Diagnostics,Pack (50),CarePlus Medical,123,...,NaN,Low,10.0,NaN,10.0,10.0,10.0,NaN,0.200,-30.000

In [43]:
df_copy = df.drop(columns=to_drop)

In [44]:
df = df_copy

In [45]:
df.head()

,date,department,product_id,product_name,category,unit,supplier,quantity_received,quantity_used,unit_cost_kes,supplier_lead_time_days,department_admissions
0,2025-01-01,Emergency,MED001,Nitrile Gloves,PPE,Box (100),MedSupply Kenya,0,55,850,7,4.0
1,2025-01-01,Emergency,MED002,5ml Syringes,Injection Supplies,Box (100),AfyaMed Distributors,0,20,620,11,4.0
2,2025-01-01,Emergency,MED003,10ml Syringes,Injection Supplies,Box (100),AfyaMed Distributors,0,12,780,11,4.0
3,2025-01-01,Emergency,MED004,IV Cannulas 20G,IV Supplies,Box (50),MedSupply Kenya,0,10,1450,14,4.0
4,2025-01-01,Emergency,MED005,IV Giving Sets,IV Supplies,Box (20),HealthLink Supplies,0,9,1680,12,4.0

In [46]:
df['quantity_received'].describe()

count    17700.000000
mean         6.455650
std         58.916052
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max       1245.000000
Name: quantity_received, dtype: float64

In [47]:
df[df['quantity_received'] > 0]

,date,department,product_id,product_name,category,unit,supplier,quantity_received,quantity_used,unit_cost_kes,supplier_lead_time_days,department_admissions
465,2025-01-07,ICU,MED001,Nitrile Gloves,PPE,Box (100),MedSupply Kenya,855,40,850,7,1.0
620,2025-01-09,ICU,MED006,Sterile Gauze 10x10cm,Wound Care,Pack (100),MedSupply Kenya,415,18,540,7,2.0
627,2025-01-09,ICU,MED013,Examination Gloves,PPE,Box (100),MedSupply Kenya,550,36,690,6,2.0
628,2025-01-09,ICU,MED014,Cotton Wool,Wound Care,Pack (500g),HealthLink Supplies,210,15,320,7,2.0
692,2025-01-10,ICU,MED003,10ml Syringes,Injection Supplies,Box (100),AfyaMed Distributors,265,13,780,11,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...
17569,2025-08-23,ICU,MED005,IV Giving Sets,IV Supplies,Box (20),HealthLink Supplies,210,5,1680,11,2.0
17577,2025-08-23,ICU,MED013,Examination Gloves,PPE,Box (100),MedSupply Kenya,815,38,690,7,2.0
17641,2025-08-24,ICU,MED002,5ml Syringes,Injection Supplies,Box (100),AfyaMed Distributors,345,18,620,12,1.0
17642,2025-08-24,ICU,MED003,10ml Syringes,Injection Supplies,Box (100),AfyaMed Distributors,205,11,780,12,1.0
17645,2025-08-24,ICU,MED006,Sterile Gauze 10x10cm,Wound Care,Pack (100),MedSupply Kenya,440,18,540,7,1.0

In [48]:
# get rows between 465 and 990 and then to filter out product_name = Nitrile gloves
subset = df.iloc[465:990].query("product_name == 'Nitrile Gloves'")

subset['quantity_used'].sum()

np.int64(942)

In [49]:
df.columns

Index(['date', 'department', 'product_id', 'product_name', 'category', 'unit',
       'supplier', 'quantity_received', 'quantity_used', 'unit_cost_kes',
       'supplier_lead_time_days', 'department_admissions'],
      dtype='object')

In [50]:
df[['department']].value_counts()

department
Emergency     3540
ICU           3540
Maternity     3540
Outpatient    3540
Theatre       3540
Name: count, dtype: int64

In [51]:
df[['category']].value_counts()

category
Diagnostics           3540
IV Supplies           3540
PPE                   3540
Wound Care            2360
Injection Supplies    2360
Disinfection          1180
Urology               1180
Name: count, dtype: int64

In [52]:
df[['product_name']].value_counts()

product_name
10ml Syringes             1180
5ml Syringes              1180
Alcohol Swabs             1180
Cotton Wool               1180
Examination Gloves        1180
IV Cannulas 20G           1180
IV Extension Sets         1180
IV Giving Sets            1180
Malaria RDT Kits          1180
Nitrile Gloves            1180
Pregnancy Test Kits       1180
Specimen Containers       1180
Sterile Gauze 10x10cm     1180
Surgical Masks            1180
Urinary Catheters 16Fr    1180
Name: count, dtype: int64

In [53]:
df[['unit']].value_counts()

unit
Box (100)      5900
Box (50)       3540
Box (25)       2360
Box (10)       1180
Box (20)       1180
Pack (100)     1180
Pack (50)      1180
Pack (500g)    1180
Name: count, dtype: int64

# ToDo
Standardize (Box(100), Pack(100)), (Box(50), Pack(50)), leave pack(500g) as is

In [54]:
df[df['unit'] == 'Box (100)']

,date,department,product_id,product_name,category,unit,supplier,quantity_received,quantity_used,unit_cost_kes,supplier_lead_time_days,department_admissions
0,2025-01-01,Emergency,MED001,Nitrile Gloves,PPE,Box (100),MedSupply Kenya,0,55,850,7,4.0
1,2025-01-01,Emergency,MED002,5ml Syringes,Injection Supplies,Box (100),AfyaMed Distributors,0,20,620,11,4.0
2,2025-01-01,Emergency,MED003,10ml Syringes,Injection Supplies,Box (100),AfyaMed Distributors,0,12,780,11,4.0
7,2025-01-01,Emergency,MED008,Alcohol Swabs,Disinfection,Box (100),AfyaMed Distributors,0,11,390,10,4.0
12,2025-01-01,Emergency,MED013,Examination Gloves,PPE,Box (100),MedSupply Kenya,0,41,690,9,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...
17685,2025-08-24,Theatre,MED001,Nitrile Gloves,PPE,Box (100),MedSupply Kenya,0,37,850,7,2.0
17686,2025-08-24,Theatre,MED002,5ml Syringes,Injection Supplies,Box (100),AfyaMed Distributors,0,10,620,10,2.0
17687,2025-08-24,Theatre,MED003,10ml Syringes,Injection Supplies,Box (100),AfyaMed Distributors,0,10,780,10,2.0
17692,2025-08-24,Theatre,MED008,Alcohol Swabs,Disinfection,Box (100),AfyaMed Distributors,0,15,390,10,2.0
17697,2025-08-24,Theatre,MED013,Examination Gloves,PPE,Box (100),MedSupply Kenya,0,27,690,9,2.0

In [55]:
df.groupby('product_id')['unit'].nunique()

product_id
MED001    1
MED002    1
MED003    1
MED004    1
MED005    1
MED006    1
MED007    1
MED008    1
MED009    1
MED010    1
MED011    1
MED012    1
MED013    1
MED014    1
MED015    1
Name: unit, dtype: int64

In [56]:
df.columns

Index(['date', 'department', 'product_id', 'product_name', 'category', 'unit',
       'supplier', 'quantity_received', 'quantity_used', 'unit_cost_kes',
       'supplier_lead_time_days', 'department_admissions'],
      dtype='object')

In [57]:
df['supplier'].value_counts()

supplier
MedSupply Kenya         5900
HealthLink Supplies     4720
AfyaMed Distributors    3540
CarePlus Medical        3540
Name: count, dtype: int64

In [59]:
# Data preparation
df.columns

Index(['date', 'department', 'product_id', 'product_name', 'category', 'unit',
       'supplier', 'quantity_received', 'quantity_used', 'unit_cost_kes',
       'supplier_lead_time_days', 'department_admissions'],
      dtype='object')

In [ ]:
# Derived features
# Columns - 'day_of_week', 'month', 'is_weekend', (lag_1d_usage, lag_7d_usage, lag_30d_usage, rolling_avg_7d_usage, rolling_avg_14d_usage, rolling_avg_30d_usage,  rolling_std_7d_usage, rolling_std_14d_usage, rolling_std_30d_usage - grouped per product_id + department), trend_slope_7, trend_slope_30,